version: '3.3' 
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./:/app
    ports:
      - 8080:8080
