version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD:/app
    ports:
      - 8080:8080
